host: 0.0.0.0
port: 8888
channels:
  - tgsearchers6
  - tgsearchers4
  - Aliyun_4K_Movies

log_level: info
# 日志文件路径，留空则不生成文件
log_file: logs/app.log

# 查询 tg 时的并发数
concurrency: 6
# 搜索结果内存缓存最大数量
# 超过该数量后，会淘汰最旧的条目
max_cache_size: 1024
# 搜索结果缓存时间，单位：秒
# 超过该时间后，会淘汰该条目
cache_ttl: 300
